name: test-publish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      shell: bash
      run: |
        pip install nbdev
        pip install .
        echo $${{ secrets.GITHUB_TOKEN  }} > token
      
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Test Action
      uses: ./action/publish
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
